language: node_js
node_js:
- 0.10.0
- 4.0.0
script:
- ./node_modules/grunt-cli/bin/grunt test
env:
  global:
  - secure: E1sJrfVvKkAxM7bo0Co9lMNDUi7eAusnlTgnVWv1nd+f6WTFyxjevpxEvSDjEWNyWfGKXMbOpmdzSHQMZs3Vyb8yd+E0lUqVAneGMOq4o/rsAvQglT90kb4vOFzSwG1uDNawzXztIebMwu7VQ/ZTo+4P39FBgLuhvgPz8/OhAh8=
  - secure: ovQuhJSjEE2MdHoPS775iBplKHTX/yUsMaFzm/4Y3VEUWdH+caLfEami19PuhS36Bn8+V6scvb5yrH44aBu/ZD6F5CoPfRj094OTunUOEJjCTJ7RqNi6XKhNRX/zt0rgpaw6TgY8NmhZLo+GLPDnp0EGQPkByHd9Imm16YXPhzE=
  - secure: gtYZONIXoPpIzKR31er/mt5TfbIoNj96CE3dJ+f/fCTNlr8ACHivTXpoTZqQMurz3cne+Pla71mc8x8/uK7CxnfAjt2HMAcz6jtLYmg7Z5/QBAVMEtzv9tMjxCY1NZQOjVWLcXg3vpJeg/ZVgutszLK1mkYnknIH3maKZhK9ITs=
